from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from rentalapp import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.role_home, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="dashboard"), name="logout"),
    path("search/", views.global_search, name="global_search"),
    path("properties/", views.property_list, name="property_list"),
    path("properties/<int:pk>/", views.property_detail, name="property_detail"),
    path("units/", views.unit_list, name="unit_list"),
    path("units/<int:pk>/", views.unit_detail, name="unit_detail"),
    path("tenants/", views.tenant_list, name="tenant_list"),
    path("tenants/<int:pk>/", views.tenant_detail, name="tenant_detail"),
    path("leases/", views.lease_list, name="lease_list"),
    path("leases/<int:pk>/", views.lease_detail, name="lease_detail"),
    path("leases/<int:pk>/activate/", views.lease_activate, name="lease_activate"),
    path("leases/<int:pk>/renew/", views.lease_renew, name="lease_renew"),
    path("leases/<int:pk>/close/", views.lease_close, name="lease_close"),
    path("leases/<int:pk>/charges/", views.lease_charge, name="lease_charge"),
    path("lease-notices/", views.notice_list, name="notice_list"),
    path("lease-amendments/", views.amendment_list, name="amendment_list"),
    path("lease-amendments/<int:pk>/approve/", views.amendment_approve, name="amendment_approve"),
    path("applications/", views.application_list, name="application_list"),
    path("applications/<int:pk>/decision/", views.application_decide, name="application_decide"),
    path("payments/", views.payment_list, name="payment_list"),
    path("payments/record/", views.payment_create, name="payment_create"),
    path("payments/<int:pk>/receipt/", views.receipt_detail, name="receipt_detail"),
    path("payments/<int:pk>/void/", views.payment_void, name="payment_void"),
    path("payments/<int:pk>/refund/", views.payment_refund, name="payment_refund"),
    path("arrears/", views.arrears, name="arrears"),
    path("deposits/", views.deposit_list, name="deposit_list"),
    path("reconciliation/", views.reconciliation_list, name="reconciliation_list"),
    path("maintenance/", views.maintenance_list, name="maintenance_list"),
    path("maintenance/<int:pk>/transition/", views.maintenance_transition, name="maintenance_transition"),
    path("inspections/", views.inspection_list, name="inspection_list"),
    path("inspections/<int:pk>/", views.inspection_detail, name="inspection_detail"),
    path("inspections/<int:pk>/complete/", views.inspection_complete, name="inspection_complete"),
    path("utilities/", views.utility_list, name="utility_list"),
    path("documents/", views.document_list, name="document_list"),
    path("documents/<int:pk>/download/", views.document_download, name="document_download"),
    path("communications/", views.communication_list, name="communication_list"),
    path("portfolio/setup/", views.portfolio_setup, name="portfolio_setup"),
    path("expenses/", views.expense_list, name="expense_list"),
    path("owner-statements/", views.owner_statement_list, name="owner_statement_list"),
    path("owner-statements/<int:pk>/", views.owner_statement_detail, name="owner_statement_detail"),
    path("owner-statements/<int:pk>/action/", views.owner_statement_action, name="owner_statement_action"),
    path("reports/", views.reports, name="reports"),
    path("reports/export/", views.reports_export, name="reports_export"),
    path("audit-logs/", views.audit_log_list, name="audit_logs"),
    path("portal/tenant/", views.tenant_portal, name="tenant_portal"),
    path("portal/landlord/", views.landlord_portal, name="landlord_portal"),

    # Non-breaking aliases for the original prototype routes.
    path("add_property/", views.property_list, name="add_property_page"),
    path("add_Unit/", views.unit_list, name="add_Unit_page"),
    path("add_Tenant/", views.tenant_list, name="add_Tenant_page"),
    path("add_Payment/", views.payment_list, name="add_Payment_page"),
    path("add_MaintenanceRequest/", views.maintenance_list, name="add_MaintenanceRequest_page"),
]
