# Generated by Django 6.0.6 on 2026-07-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='names',
        ),
    ]
