# Generated by Django 6.0.6 on 2026-07-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0003_booking_location_broker_landlord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='property',
            new_name='propertyy',
        ),
    ]
