# Generated by Django 6.0.6 on 2026-07-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0004_rename_property_unit_propertyy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='user',
            new_name='user_name',
        ),
    ]
