# Generated by Django 6.0.7 on 2026-08-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0007_expense_lease_paymentallocation_receipt_rentcharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
    ]
