# Generated by Django 6.0.7 on 2026-08-13 12:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import rentalapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0008_expense_status_expense_void_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('recipient_name', models.CharField(max_length=140)),
                ('recipient_address', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=140)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('related_type', models.CharField(blank=True, max_length=80)),
                ('related_id', models.CharField(blank=True, max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=140)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('identification', 'Identification'), ('application', 'Application'), ('lease', 'Lease'), ('inspection', 'Inspection'), ('receipt', 'Receipt'), ('invoice', 'Invoice'), ('notice', 'Notice'), ('other', 'Other')], default='other', max_length=30)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=rentalapp.models.document_upload_path)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('inspection_type', models.CharField(choices=[('move_in', 'Move-in'), ('routine', 'Routine'), ('move_out', 'Move-out')], max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('acknowledged', 'Tenant acknowledged'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('electricity_reading', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('water_reading', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('keys_issued', models.PositiveSmallIntegerField(default=0)),
                ('tenant_acknowledged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-scheduled_for',),
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=140)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('estimated_damage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ('area', 'item'),
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('replacement_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('unit', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LeaseAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amendment_type', models.CharField(choices=[('rent_change', 'Rent change'), ('term_extension', 'Term extension'), ('occupant_change', 'Occupant change'), ('other', 'Other')], max_length=30)),
                ('effective_date', models.DateField()),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-effective_date',),
            },
        ),
        migrations.CreateModel(
            name='LeaseNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('notice_type', models.CharField(choices=[('tenant_termination', 'Tenant termination'), ('landlord_termination', 'Landlord termination'), ('non_renewal', 'Non-renewal'), ('renewal_offer', 'Renewal offer')], max_length=30)),
                ('notice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('served', 'Served'), ('acknowledged', 'Acknowledged'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-notice_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='in_app', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=140)),
                ('body', models.TextField(help_text='Use plain text. Merge fields can be filled before sending.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OwnerStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('rent_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('management_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payout_reference', models.CharField(blank=True, max_length=140)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-period_end', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('cash', 'Cash'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('bank', 'Bank transfer/deposit'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], max_length=40)),
                ('external_reference', models.CharField(max_length=140)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payer', models.CharField(blank=True, max_length=140)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('disputed', 'Disputed'), ('ignored', 'Ignored')], default='unmatched', max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-transaction_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('applicant_name', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=30)),
                ('current_address', models.CharField(blank=True, max_length=255)),
                ('employer', models.CharField(blank=True, max_length=140)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('requested_move_in', models.DateField()),
                ('occupants', models.PositiveSmallIntegerField(default=1)),
                ('guarantor_name', models.CharField(blank=True, max_length=140)),
                ('guarantor_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('screening', 'Screening'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('converted', 'Converted to lease')], default='submitted', max_length=20)),
                ('screening_notes', models.TextField(blank=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SecurityDepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('receipt', 'Deposit received'), ('deduction', 'Deposit deduction'), ('refund', 'Deposit refund'), ('adjustment_in', 'Positive adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=20)),
                ('void_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('transaction_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('administrator', 'Administrator'), ('manager', 'Property manager'), ('accountant', 'Accountant'), ('maintenance', 'Maintenance officer'), ('landlord', 'Landlord'), ('tenant', 'Tenant')], default='viewer', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('user__first_name', 'user__username'),
            },
        ),
        migrations.CreateModel(
            name='UtilityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utility_type', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('gas', 'Gas')], max_length=20)),
                ('meter_number', models.CharField(max_length=80)),
                ('unit_rate', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('standing_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('unit', 'utility_type'),
            },
        ),
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reading', models.DecimalField(decimal_places=3, max_digits=14)),
                ('previous_reading', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('consumption', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-reading_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('legal', 'Legal'), ('other', 'Other')], default='maintenance', max_length=30)),
                ('contact_person', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_id', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('bank_details', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='rentcharge',
            name='unique_rent_period_per_lease',
        ),
        migrations.AddField(
            model_name='landlord',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='landlord',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='landlord',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landlord',
            name='management_fee_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='landlord',
            name='payout_method',
            field=models.CharField(choices=[('bank', 'Bank transfer'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('cash', 'Cash')], default='bank', max_length=20),
        ),
        migrations.AddField(
            model_name='landlord',
            name='payout_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='landlord',
            name='tax_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='lease',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='renewal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='rentalapp.lease'),
        ),
        migrations.AddField(
            model_name='lease',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='quoted_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='tenant_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentcharge',
            name='charge_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('service_charge', 'Service charge'), ('water', 'Water'), ('electricity', 'Electricity'), ('late_fee', 'Late fee'), ('damage', 'Damage'), ('discount', 'Discount/credit'), ('other', 'Other')], default='rent', max_length=30),
        ),
        migrations.AddField(
            model_name='rentcharge',
            name='source_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='rentcharge',
            constraint=models.UniqueConstraint(fields=('lease', 'period', 'charge_type'), name='unique_charge_type_period_per_lease'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_rental_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='rentalapp.lease'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='rentalapp.unit'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentalapp.inspection'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='rentalapp.unit'),
        ),
        migrations.AddField(
            model_name='leaseamendment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_lease_amendments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaseamendment',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='rentalapp.lease'),
        ),
        migrations.AddField(
            model_name='leasenotice',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='rentalapp.lease'),
        ),
        migrations.AddField(
            model_name='leasenotice',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='served_lease_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerstatement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_owner_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerstatement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='rentalapp.landlord'),
        ),
        migrations.AddField(
            model_name='ownerstatement',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_statements', to='rentalapp.property'),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_payment_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='rentalapp.payment'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_rental_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_application', to='rentalapp.tenant'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='rentalapp.unit'),
        ),
        migrations.AddField(
            model_name='lease',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease', to='rentalapp.rentalapplication'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('active', 'expiring'))), fields=('unit',), name='one_current_lease_per_unit'),
        ),
        migrations.AddField(
            model_name='securitydeposittransaction',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_transactions', to='rentalapp.lease'),
        ),
        migrations.AddField(
            model_name='securitydeposittransaction',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_deposit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilitymeter',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_meters', to='rentalapp.unit'),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utility_reading', to='rentalapp.rentcharge'),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='rentalapp.utilitymeter'),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_utility_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='rentalapp.vendor'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='rentalapp.vendor'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['object_type', 'object_id'], name='rentalapp_d_object__2f8ce9_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('unit', 'name', 'serial_number'), name='unique_unit_inventory_item'),
        ),
        migrations.AddConstraint(
            model_name='ownerstatement',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='valid_owner_statement_period'),
        ),
        migrations.AddConstraint(
            model_name='ownerstatement',
            constraint=models.UniqueConstraint(fields=('owner', 'property', 'period_start', 'period_end'), name='unique_owner_statement_period'),
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliation',
            constraint=models.UniqueConstraint(fields=('provider', 'external_reference'), name='unique_provider_transaction'),
        ),
        migrations.AddConstraint(
            model_name='securitydeposittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_deposit_transaction'),
        ),
        migrations.AddConstraint(
            model_name='utilitymeter',
            constraint=models.UniqueConstraint(fields=('unit', 'utility_type', 'meter_number'), name='unique_unit_meter'),
        ),
        migrations.AddConstraint(
            model_name='utilityreading',
            constraint=models.UniqueConstraint(fields=('meter', 'reading_date'), name='unique_meter_reading_date'),
        ),
    ]
