# Generated by Django 6.0.7 on 2026-08-13 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0010_backfill_workflow_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refund_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=20)),
            ],
            options={
                'ordering': ('-refund_date', '-id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='rentcharge',
            name='unique_charge_type_period_per_lease',
        ),
        migrations.AddConstraint(
            model_name='rentcharge',
            constraint=models.UniqueConstraint(condition=models.Q(('charge_type__in', ('rent', 'service_charge', 'water', 'electricity'))), fields=('lease', 'period', 'charge_type'), name='unique_recurring_charge_period'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='rentalapp.payment'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_payment_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_payment_refund'),
        ),
    ]
